# Generated by Django 4.0.1 on 2022-01-20 18:58

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UUIDModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID идентификатор')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название провайдера')),
                ('data', models.JSONField(blank=True, max_length=10, null=True, verbose_name='Данные поиска ')),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50, verbose_name='Статус')),
                ('search_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airflow.uuidmodel')),
            ],
        ),
    ]
