# Generated by Django 4.0.1 on 2022-01-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresult',
            old_name='name',
            new_name='provider_name',
        ),
    ]
