# Generated by Django 4.0.1 on 2022-01-21 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0002_rename_name_searchresult_provider_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provaider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название провайдера')),
            ],
            options={
                'verbose_name': 'Провайдер',
            },
        ),
        migrations.AlterModelOptions(
            name='searchresult',
            options={'verbose_name': 'Результаты пойска'},
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='provider_name',
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='search_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='airflow.uuidmodel'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='provider',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='airflow.provaider'),
        ),
    ]
