# Generated by Django 4.0.1 on 2022-01-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0003_provaider_alter_searchresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provaider',
            name='branch_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Код провайдера'),
        ),
    ]
