# Generated by Django 4.0.1 on 2022-01-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0004_provaider_branch_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provaider',
            new_name='Provider',
        ),
    ]
