# Generated by Django 4.0.1 on 2022-01-21 06:27

from django.db import migrations, models


DEFAULT_TYPES = [
    'Arystan',
    'Bastian'
]


def create_default(apps, schema):
    Provider = apps.get_model('airflow', 'Provider')
    Provider.objects.bulk_create(
        [Provider(name=name)
         for name in DEFAULT_TYPES]
    )


def remove_default(apps, schema):
    Provider = apps.get_model('airflow', 'Provider')
    Provider.objects.filter(bracnh_code__in=DEFAULT_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0005_rename_provaider_provider'),
    ]

    operations = [
        migrations.RunPython(
            create_default,
            reverse_code=remove_default
        )
    ]
