# Generated by Django 3.2.11 on 2022-01-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0006_alter_provider_branch_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Данные курса')),
            ],
        ),
        migrations.RemoveField(
            model_name='provider',
            name='branch_code',
        ),
    ]
